sources:
  - name: Fake API
    handler:
      jsonSchema:
        baseUrl: https://not-existing-api.com/API
        operations:
          - type: Query
            field: me
            path: /wp/v2/user/me
            method: GET
            responseSchema: ./json-schemas/user.json
          - type: Mutation
            field: createUser
            path: /wp/v2/users
            method: POST
            requestSchema: ./json-schemas/userInput.json
            responseSchema: ./json-schemas/user.json
          - type: Mutation
            field: updateUser
            path: /wp/v2/users/{args.id}
            method: POST
            requestSchema: ./json-schemas/userInput.json
            responseSchema: ./json-schemas/user.json
