sources:
  - name: Fake API
    handler:
      jsonSchema:
        baseUrl: https://not-existing-api.com/API
        operations:
          - type: Query
            field: users
            path: /users
            method: GET
            responseSchema: ./json-schemas/users.json
          - type: Mutation
            field: updateUsers
            path: /users/{args.id}
            method: PUT
            responseSchema: ./json-schemas/users.json